src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quizzes/', include('quiz.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/quiz/models.py
import datetime

from core.models import BaseModel
from core.utils import generate_uuid

from dateutil.relativedelta import relativedelta

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.timezone import utc


class Exam(BaseModel):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL(models.IntegerChoices):
        BASIC = 0, 'Basic'
        MIDDLE = 1, 'Middle'
        ADVANCED = 2, 'Advanced'

    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    title = models.CharField(max_length=64)
    description = models.TextField(null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL.choices, default=LEVEL.BASIC)

    def questions_count(self):
        return self.questions.count()

    def __str__(self):
        return self.title


class Question(BaseModel):
    exam = models.ForeignKey(Exam, related_name='questions', on_delete=models.CASCADE)
    order_num = models.PositiveSmallIntegerField()
    text = models.CharField(max_length=2048)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    text = models.CharField(max_length=1024)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Result(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(get_user_model(), related_name='results', on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, related_name='results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    current_order_number = models.PositiveSmallIntegerField(null=True)
    num_correct_answers = models.PositiveSmallIntegerField(default=0)
    num_incorrect_answers = models.PositiveSmallIntegerField(default=0)

    def update_result(self, order_number, question, selected_choices):
        correct_choice = [choice.is_correct for choice in question.choices.all()]
        correct_answer = True
        for z in zip(selected_choices, correct_choice):
            correct_answer &= (z[0] == z[1])

        self.num_correct_answers += int(correct_answer)
        self.num_incorrect_answers += 1 - int(correct_answer)
        self.current_order_number = order_number

        if order_number == question.exam.questions_count():
            self.state = self.STATE.FINISHED

            self.user.rating = self.user.rating + max(0, self.num_correct_answers - self.num_incorrect_answers)
            self.user.save()

        self.save()

    def time_diff(self):
        time_diff = relativedelta(datetime.datetime.utcnow().replace(tzinfo=utc), self.create_timestamp)
        return "%dh:%dm:%ds" % (time_diff.hours, time_diff.minutes, time_diff.seconds)

    def success_rate(self):
        return (self.num_correct_answers / (self.num_correct_answers + self.num_incorrect_answers)) * 100

    def points(self):
        return max(0, self.num_correct_answers - self.num_incorrect_answers)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quiz -
        {% block title%}
            Home
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <style>{% block custom_css %}{% endblock %}</style>
</head>
<body>
  {% include 'includes/nav_bar.html' %}

  <div class="container mt-4 pt-4">
    <div class="border rounded text-center p-3 m-3 mb-5 bg-light shadow">
      <h1>{% block header %}Welcome to Quiz!!!{% endblock %}</h1>
    </div>

    {% include 'includes/messages.html' %}

    {% block content %}{% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
          crossorigin="anonymous"></script>
</body>
</html>

src/templates/flat_page.html
{% extends 'base.html' %}

{% block title %}{{ flatpage.title }}{% endblock %}

{% block content %}
    {{ flatpage.content }}
{% endblock %}

src/templates/index.html
{% extends 'base.html' %}

{% block content %}
{#    <h4>perms.quiz.add_result: {{ perms.quiz.add_result }}</h4>#}
{#    <h4>perms.quiz.view_result: {{ perms.quiz.view_result }}</h4>#}
{#    <h4>perms.quiz.change_result: {{ perms.quiz.change_result }}</h4>#}
{#    <h4>perms.quiz.delete_result: {{ perms.quiz.delete_result }}</h4>#}
{#    <h4>perms.accounts.view_statistics: {{ perms.accounts.view_statistics }}</h4>#}
{% endblock %}


{# <app_name>.<perm>_<model> #}