src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quizzes/', include('quiz.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/quiz/urls.py
from django.urls import path

from .views import ExamDetailView, ExamListView, ExamQuestionView, ExamResultCreateView, ExamResultDeleteView, \
    ExamResultDetailView, ExamResultListView, ExamResultUpdateView

app_name = 'quizzes'

urlpatterns = [
    path('', ExamListView.as_view(), name='list'),
    path('result_list/', ExamResultListView.as_view(), name='result_list'),
    path('<uuid:uuid>/', ExamDetailView.as_view(), name='details'),
    path('<uuid:uuid>/result/create/', ExamResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/details/', ExamResultDetailView.as_view(), name='result_details'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/update/', ExamResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/delete/', ExamResultDeleteView.as_view(), name='result_delete'),
    path('<uuid:uuid>/result/<uuid:result_uuid>/question/next/', ExamQuestionView.as_view(), name='question'),
]

src/quiz/models.py
import datetime

from core.models import BaseModel
from core.utils import generate_uuid

from dateutil.relativedelta import relativedelta

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.timezone import utc


class Exam(BaseModel):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL(models.IntegerChoices):
        BASIC = 0, 'Basic'
        MIDDLE = 1, 'Middle'
        ADVANCED = 2, 'Advanced'

    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    title = models.CharField(max_length=64)
    description = models.TextField(null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL.choices, default=LEVEL.BASIC)

    def questions_count(self):
        return self.questions.count()

    def __str__(self):
        return self.title


class Question(BaseModel):
    exam = models.ForeignKey(Exam, related_name='questions', on_delete=models.CASCADE)
    order_num = models.PositiveSmallIntegerField()
    text = models.CharField(max_length=2048)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    text = models.CharField(max_length=1024)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Result(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(get_user_model(), related_name='results', on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, related_name='results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    current_order_number = models.PositiveSmallIntegerField(null=True)
    num_correct_answers = models.PositiveSmallIntegerField(default=0)
    num_incorrect_answers = models.PositiveSmallIntegerField(default=0)

    def update_result(self, order_number, question, selected_choices):
        correct_choice = [choice.is_correct for choice in question.choices.all()]
        correct_answer = True
        for z in zip(selected_choices, correct_choice):
            correct_answer &= (z[0] == z[1])

        self.num_correct_answers += int(correct_answer)
        self.num_incorrect_answers += 1 - int(correct_answer)
        self.current_order_number = order_number

        if order_number == question.exam.questions_count():
            self.state = self.STATE.FINISHED

            self.user.rating = self.user.rating + max(0, self.num_correct_answers - self.num_incorrect_answers)
            self.user.save()

        self.save()

    def time_diff(self):
        time_diff = relativedelta(datetime.datetime.utcnow().replace(tzinfo=utc), self.create_timestamp)
        return "%dh:%dm:%ds" % (time_diff.hours, time_diff.minutes, time_diff.seconds)

    def success_rate(self):
        return (self.num_correct_answers / (self.num_correct_answers + self.num_incorrect_answers)) * 100

    def points(self):
        return max(0, self.num_correct_answers - self.num_incorrect_answers)

src/quiz/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BaseInlineFormSet, ModelForm, modelformset_factory

from .models import Choice


class ChoiceInlineFormSet(BaseInlineFormSet):
    def clean(self):
        num_correct_answer = sum(1 for form in self.forms if form.cleaned_data['is_correct'])

        if num_correct_answer == 0:
            raise ValidationError('Необходимо выбрать как минимум 1 правильный ответ')

        if num_correct_answer == len(self.forms):
            raise ValidationError('Не могут быть все ответы правильными')


class QuestionInlineFormSet(BaseInlineFormSet):
    def clean(self):
        if not (self.instance.QUESTION_MIN_LIMIT <= len(self.forms) <= self.instance.QUESTION_MAX_LIMIT):
            raise ValidationError('Кол-во вопросов должно быть в диапазоне от {} до {}'.format(
                self.instance.QUESTION_MIN_LIMIT,
                self.instance.QUESTION_MAX_LIMIT
            ))

        order_num = [form.cleaned_data['order_num'] for form in self.forms]
        if min(order_num) != 1:
            raise ValidationError('Нумерация должна начинаться с 1')
        if max(order_num) != len(self.forms):
            raise ValidationError('Максимальный порядковый номер не может быть больше количества вопросов в тесте')
        if len(order_num) != len(set(order_num)):
            raise ValidationError('Неправильная нумерация')


class ChoiceForm(ModelForm):
    is_selected = forms.BooleanField(required=False)

    class Meta:
        model = Choice
        fields = ['text']


ChoicesFormSet = modelformset_factory(
    model=Choice,
    form=ChoiceForm,
    extra=0
)

src/quiz/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from django.views.generic.list import MultipleObjectMixin

from .forms import ChoicesFormSet
from .models import Exam, Question, Result


class ExamListView(LoginRequiredMixin, ListView):
    model = Exam
    template_name = 'exams/list.html'
    context_object_name = 'exams'


class ExamDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = Exam
    template_name = 'exams/details.html'
    context_object_name = 'exam'
    pk_url_kwarg = 'uuid'
    paginate_by = 3

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('uuid')
        # return self.get_queryset().get(uuid=uuid)
        return self.model.objects.get(uuid=uuid)

    def get_context_data(self, **kwargs):
        # context = super().get_context_data(**kwargs)
        # context['result_list'] = Result.objects.filter(
        #     exam=self.get_object(),
        #     user=self.request.user
        # ).order_by('state')
        context = super().get_context_data(object_list=self.get_queryset(), **kwargs)

        return context

    def get_queryset(self):
        return Result.objects.filter(
            exam=self.get_object(),
            user=self.request.user
        ).order_by('state')


class ExamResultCreateView(LoginRequiredMixin, CreateView):
    def post(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid')
        result = Result.objects.create(
            user=request.user,
            exam=Exam.objects.get(uuid=uuid),
            state=Result.STATE.NEW,
            current_order_number=0
        )

        result.save()

        return HttpResponseRedirect(reverse(
            'quizzes:question',
            kwargs={
                'uuid': uuid,
                'result_uuid': result.uuid,
                # 'order_number': 1,
            }
        ))


class ExamQuestionView(LoginRequiredMixin, UpdateView):
    def get(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid')
        # order_number = kwargs.get('order_number')
        result = Result.objects.get(uuid=kwargs['result_uuid'])

        question = Question.objects.get(
            exam__uuid=uuid,
            # order_num=order_number
            order_num=result.current_order_number + 1
        )

        choices = ChoicesFormSet(queryset=question.choices.all())

        return render(
            request,
            'exams/question.html',
            context={
                'question': question,
                'choices': choices
            }
        )

    def post(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid')
        result_uuid = kwargs.get('result_uuid')
        result = Result.objects.get(uuid=result_uuid)
        # order_number = kwargs.get('order_number')
        order_number = result.current_order_number + 1

        question = Question.objects.get(
            exam__uuid=uuid,
            order_num=order_number
        )

        choices = ChoicesFormSet(data=request.POST)
        selected_choices = ['is_selected' in form.changed_data for form in choices.forms]
        if selected_choices.count(True) == 0:
            messages.warning(request, 'Выберите один или несколько правильных ответов')
            order_number = result.current_order_number
        elif selected_choices.count(True) == len(selected_choices):
            messages.warning(request, 'Все ответы не могут быть правильными')
            order_number = result.current_order_number
        else:
            result = Result.objects.get(uuid=result_uuid)
            result.update_result(order_number, question, selected_choices)

        if result.state == Result.STATE.FINISHED:
            return HttpResponseRedirect(reverse(
                'quizzes:result_details',
                kwargs={
                    'uuid': uuid,
                    'result_uuid': result.uuid,
                }
            ))

        return HttpResponseRedirect(reverse(
            'quizzes:question',
            kwargs={
                'uuid': uuid,
                'result_uuid': result.uuid,
                # 'order_number': order_number + 1,
            }
        ))


class ExamResultDetailView(LoginRequiredMixin, DetailView):
    model = Result
    template_name = 'results/details.html'
    context_object_name = 'result'
    pk_url_kwarg = 'uuid'

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('result_uuid')
        return self.get_queryset().get(uuid=uuid)


class ExamResultUpdateView(LoginRequiredMixin, UpdateView):
    # permission_required = ['accounts.view_statistics']

    def get(self, request, *args, **kwargs):
        uuid = kwargs['uuid']
        result_uuid = kwargs['result_uuid']
        user = request.user

        result = Result.objects.get(
            user=user,
            uuid=result_uuid
        )

        return HttpResponseRedirect(reverse(
            'quizzes:question',
            kwargs={
                'uuid': uuid,
                'result_uuid': result.uuid,
                # 'order_number': result.current_order_number + 1,
            }
        ))


class ExamResultDeleteView(LoginRequiredMixin, DeleteView):
    def get(self, request, *args, **kwargs):
        result_uuid = kwargs['result_uuid']
        user = request.user

        result = Result.objects.get(
            user=user,
            uuid=result_uuid
        )
        result.delete()

        return HttpResponseRedirect(reverse('quizzes:result_list'))


class ExamResultListView(LoginRequiredMixin, ListView):
    model = Result
    template_name = 'results/list.html'
    context_object_name = 'results'
    paginate_by = 5

    def get_queryset(self):
        user = self.request.user
        return Result.objects.filter(user=user)

src/quiz/templates/exams/details.html
{% extends 'base.html' %}

{% block title %}
    Описание теста
{% endblock %}

{% block header %}
    Тест: {{ exam.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td>Описание</td>
                            <td>{{ exam.description }}</td>
                        </tr>
                        <tr>
                            <td>Кол-во вопросов</td>
{#                            <td>{{ exam.questions.count }}</td>#}
                            <td>{{ exam.questions_count }}</td>
                        </tr>
                        <tr>
                            <td>Кол-во запусков</td>
                            <td>{{ exam.results.count }}</td>
                        </tr>
                        <tr>
                            <td>Лучший результат</td>
                            <td>N/A</td>
                        </tr>
                        <tr>
                            <td>Кто получил лучший результат</td>
                            <td>N/A</td>
                        </tr>
                        <tr>
                            <td>Последний запуск</td>
                            <td>N/A</td>
                        </tr>
                    </tbody>
              </table>
            </div>
        </div>
        <div class="row">
            <form action="{% url 'quizzes:result_create' exam.uuid %}" method="post"
                  class="d-flex justify-content-center mt-5 mb-2">
                {% csrf_token %}
                <a class="btn btn-primary m-3" href="{% url 'quizzes:list' %}">Вернуться к списку тестов</a>
                <input class="btn btn-success m-3" type="submit" value="СТАРТ >">
            </form>
        </div>
{#        {% if result_list %}#}
        {% if object_list %}
        <table class="table table-striped table-hover">
            <tr>
                <th></th>
                <th>Дата старта</th>
                <th>Баллы</th>
                <th>Статус</th>
                <th>Действия</th>
            </tr>
{#            {% for result in result_list %}#}
            {% for result in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ result.create_timestamp }}</td>
                <td>{{ result.points }}</td>
                <td>{{ result.get_state_display }}</td>
                <td>
                    {% if result.state == result.STATE.NEW %}
                        <a class="btn btn-warning" href="{% url 'quizzes:result_update' exam.uuid result.uuid %}">
                            Продолжить
                        </a>
                        <a class="btn btn-danger" href="{% url 'quizzes:result_delete' exam.uuid result.uuid %}">
                            Удалить
                        </a>
                    {% else %}
                        <a class="btn btn-success" href="{% url 'quizzes:result_details' exam.uuid result.uuid  %}">
                            Посмотреть
                        </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        {% if is_paginated %}
        <div class="p-1 m-1">
            {% include 'includes/pagination.html' %}
        </div>
        {% endif %}
        {% endif %}
    </div>
{% endblock %}

src/quiz/templates/exams/list.html
{% extends 'base.html' %}

{% block title %}
    Список тестов
{% endblock %}

{% block header %}
    Список тестов
{% endblock %}

{% block content %}
    {% if exams %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th></th>
                    <th>Название</th>
                    <th>Описание</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for exam in exams %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ exam.title }}</td>
                    <td>{{ exam.description }}</td>
                    <td><a href="{% url 'quizzes:details' uuid=exam.uuid %}">Подробнее</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="p-1 m-1">
            {% include 'includes/pagination.html' %}
        </div>
    {% else %}
        <p>Тестов ещё нет здесь!</p>
    {% endif %}
{% endblock %}

src/quiz/templates/exams/question.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block title %}
    Описание теста
{% endblock %}

{% block header %}
    {{ question.order_num }}. {{ question.text }}
{#    {% with question.order_num|add:-1|multi:100|dived:question.exam.questions_count as progress_level %}#}
    {% expression '(%1 - 1) * 100 // %2' question.order_num question.exam.questions_count as progress_level %}
    <div class="progress">
      <div class="progress-bar" role="progressbar" style="width: {{ progress_level }}%"
           aria-valuenow="{{ progress_level }}" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
{#    {% endwith %}#}
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" autocomplete="off">
            {% csrf_token %}
            {{ choices.management_form }}
{#            <div class="border-button mb-3">#}
{#                Пожалуйста, выберите ОДИН правильный ответ:#}
{#            </div>#}
            {% for form in choices %}
                <div class="mt-1">
                    {{ form.is_selected }} <label for="{{ form.is_selected.id_for_label }}">
                        {{ form.text.value }}
                    </label>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success mt-5">Следующий ></button>
        </form>
    </div>
{% endblock %}