src/accounts/urls.py
from django.urls import path

from .views import AccountLoginView, AccountLogoutView, AccountRegistrationDoneView, AccountRegistrationView, \
    AccountUpdateProfileView, account_profile_view, user_activate

app_name = 'accounts'

urlpatterns = [
    path('registration/асtivate/<str:sign>/', user_activate, name='register_activate'),
    path('registration/done/', AccountRegistrationDoneView.as_view(), name='registration_done'),
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', account_profile_view, name='profile'),
    path('profile_change/', AccountUpdateProfileView.as_view(), name='profile_change'),
]

src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quizzes/', include('quiz.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/quiz/urls.py
from django.urls import path

from .views import ExamDetailView, ExamListView, ExamQuestionView, ExamResultCreateView, ExamResultDeleteView, \
    ExamResultDetailView, ExamResultListView, ExamResultUpdateView

app_name = 'quizzes'

urlpatterns = [
    path('', ExamListView.as_view(), name='list'),
    path('result_list/', ExamResultListView.as_view(), name='result_list'),
    path('<uuid:uuid>/', ExamDetailView.as_view(), name='details'),
    path('<uuid:uuid>/result/create/', ExamResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/details/', ExamResultDetailView.as_view(), name='result_details'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/update/', ExamResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/delete/', ExamResultDeleteView.as_view(), name='result_delete'),
    path('<uuid:uuid>/result/<uuid:result_uuid>/question/next/', ExamQuestionView.as_view(), name='question'),
]

src/templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
{% endif %}

src/templates/includes/nav_bar.html
{% load static %}

<nav class="navbar navbar-light fixed-top navbar-expand-lg font-weight-bold" style="background-color: #e3f2fd;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">QUIZ</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <a class="nav-link" href="{% url 'quizzes:list' %}">Exam list</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'quizzes:result_list' %}">Result list</a>
          </li>
<!--        <li class="nav-item"><a class="nav-link" href="/contacts/">Contacts</a></li>-->
<!--        <li class="nav-item"><a class="nav-link" href="/about/">About Us</a></li>-->
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {% if user.is_authenticated %}
              <img class="rounded-circle" width="30" height="30" src="{{ user.avatar.url }}" />
              {{ user.username }}
            {% else %}
              <img class="rounded-circle" width="30" height="30" src="{% static 'images/default.png' %}" />
              Кабинет
            {% endif %}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown3">
          {% if user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Выход</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Профиль {{ user.username }}</a></li>
              <li><a class="dropdown-item" href="{% url 'password_change' %}">Изменить пароль</a></li>
          {% else %}
            <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Вход</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'accounts:registration' %}">Регистрация</a></li>
          {% endif %}
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

src/templates/includes/pagination.html
<nav aria-label="Page navigation example">
  <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1{% if get_params %}&{{ get_params }}{% endif %}">&laquo; First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if get_params %}&{{ get_params }}{% endif %}">Previous</a></li>
      {% endif %}

      {% for page_num in page_obj.paginator.page_range %}
        {% if page_num == page_obj.number %}
            <li class="page-item active"><a class="page-link" href="?page={{ page_num }}{% if get_params %}&{{ get_params }}{% endif %}">{{ page_num }}</a></li>
        {% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
            <li class="page-item"><a class="page-link" href="?page={{ page_num }}{% if get_params %}&{{ get_params }}{% endif %}">{{ page_num }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% if get_params %}&{{ get_params }}{% endif %}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if get_params %}&{{ get_params }}{% endif %}">Last &raquo;</a></li>
      {% endif %}

      <!--   -->

      {#    #}

      {# comment '' #}

      {# endcomment #}
  </ul>
</nav>